use_frameworks!

platform :ios, '8.0'

target 'FindUnusedClasses_Example' do
  pod 'FindUnusedClasses', :path => '../'

  target 'FindUnusedClasses_Tests' do
    inherit! :search_paths

    
  end
end
